export const PRODUCTS = [
    {
        id: 1,
        name: 'Wireless Headphones',
        price: '$99.99',
        shortDescription: 'Noise-cancelling over-ear headphones with immersive sound.',
        description: 'Experience sound like never before with our Wireless Headphones, crafted for audiophiles and casual listeners alike. Designed with advanced noise-cancelling technology, these over-ear headphones deliver crisp highs, deep lows, and an immersive audio experience that blocks out the world around you. Whether you\'re on a flight, working from home, or just relaxing with your favorite playlist, the Bluetooth 5.0 connectivity ensures seamless pairing with all your devices. With an impressive 40-hour battery life and fast-charging capabilities, you can enjoy uninterrupted sound on the go. The ergonomic over-ear fit offers all-day comfort, making them your perfect companion for both work and play. Available in sleek Black and modern Silver.',
        image: '/images/wireless-headphones.png',
        specs: ['Bluetooth 5.0', '40-hour battery', 'Fast charging', 'Over-ear fit'],
        sizes: ['Standard'],
        colors: ['Black', 'Silver'],
    },
    {
        id: 2,
        name: 'Smartwatch',
        price: '$199.99',
        shortDescription: 'Fitness tracking smartwatch with heart rate monitor.',
        description: 'Redefine your wellness journey with our feature-packed Smartwatch, engineered to keep up with your active lifestyle. With a vibrant OLED display and sleek, lightweight design, this smartwatch is as stylish as it is functional. Track your fitness goals, monitor your heart rate, navigate with built-in GPS, and stay connected on the go with cellular capabilities. It\'s perfect for outdoor adventures or intense workouts, thanks to its water-resistant design. Choose between the compact 38mm or the more robust 42mm size to suit your wrist. Available in three elegant colors: Space Gray, Rose Gold, and Silver, this watch seamlessly blends fashion with function.',
        image: '/images/smartwatch.png',
        specs: ['OLED Display', 'GPS + Cellular', 'Water Resistant'],
        sizes: ['38mm', '42mm'],
        colors: ['Space Gray', 'Rose Gold', 'Silver'],
    },
    {
        id: 3,
        name: 'Bluetooth Speaker',
        price: '$49.99',
        shortDescription: 'Portable mini Bluetooth speaker with deep bass.',
        description: 'Unleash powerful audio in a pint-sized package with our Bluetooth Speaker. Despite its compact size, this speaker packs a punch with 360-degree sound and rich, deep bass that fills any space. Whether you\'re at a beach party, camping trip, or relaxing at home, its IPX7 waterproof rating makes it your go-anywhere, do-anything speaker. The built-in battery delivers up to 12 hours of continuous playtime, ensuring your soundtrack never skips a beat. With a rugged and stylish design, it\'s available in bold Blue, energetic Red, and classic Black to match your vibe. Take your music to the next level—anytime, anywhere.',
        image: '/images/speaker.png',
        specs: ['360° Sound', '12h Battery', 'IPX7 Waterproof'],
        sizes: ['Mini'],
        colors: ['Blue', 'Red', 'Black'],
    },
    {
        id: 4,
        name: '4K Action Camera',
        price: '$149.99',
        shortDescription: 'Compact waterproof action camera with 4K video and image stabilization.',
        description: 'Capture every adventure in stunning detail with our 4K Action Camera. Built for thrill-seekers and content creators, this compact device records ultra-high-definition video with sharp clarity and vibrant color. Whether you\'re skiing, surfing, or skydiving, its rugged waterproof design and advanced image stabilization keep your footage smooth and crisp. With built-in Wi-Fi for easy sharing, a wide-angle lens for immersive shots, and support for external memory cards, it\'s the perfect companion for capturing memories on the move. Comes in a durable case with mounting accessories for helmets, bikes, and more.',
        image: '/images/camera.png',
        specs: ['4K UHD', 'Image Stabilization', 'Waterproof up to 30m', 'Wi-Fi Connectivity'],
        sizes: ['Compact'],
        colors: ['Black', 'Camouflage'],
    },
];
